import type { IntegrationDefinition } from './types'

export const integrations: IntegrationDefinition[] = [
  {
    id: 'open-meteo',
    name: 'Weather',
    provider: 'Open-Meteo',
    description: 'Current conditions, forecasts, and location search.',
    capabilities: ['weather'],
    requiresServer: false,
    requiresKey: false,
    availability: 'available',
    attributionUrl: 'https://open-meteo.com/',
  },
  {
    id: 'coinbase',
    name: 'Crypto markets',
    provider: 'Coinbase',
    description: 'Public spot prices for selected crypto assets.',
    capabilities: ['crypto'],
    requiresServer: false,
    requiresKey: false,
    availability: 'available',
    attributionUrl: 'https://www.coinbase.com/',
  },
  {
    id: 'hacker-news',
    name: 'Hacker News',
    provider: 'Y Combinator',
    description: 'Top, new, and best Hacker News stories.',
    capabilities: ['feed'],
    requiresServer: false,
    requiresKey: false,
    availability: 'available',
    attributionUrl: 'https://news.ycombinator.com/',
  },
  {
    id: 'rss',
    name: 'RSS and Atom',
    provider: 'Built-in RSS service',
    description: 'Safely normalizes remote RSS and Atom feeds.',
    capabilities: ['feed'],
    requiresServer: true,
    requiresKey: false,
    availability: 'available',
  },
  {
    id: 'github',
    name: 'GitHub',
    provider: 'GitHub',
    description: 'Repository activity, issues, and pull requests.',
    capabilities: ['developer'],
    requiresServer: false,
    requiresKey: false,
    availability: 'planned',
  },
  {
    id: 'market-data',
    name: 'Advanced markets',
    provider: 'Configurable',
    description: 'Stocks, indexes, and expanded market data.',
    capabilities: ['markets'],
    requiresServer: true,
    requiresKey: true,
    availability: 'planned',
  },
  {
    id: 'news',
    name: 'News providers',
    provider: 'Configurable',
    description: 'Key-backed curated news sources.',
    capabilities: ['news'],
    requiresServer: true,
    requiresKey: true,
    availability: 'planned',
  },
]
